# Generated by Django 3.1.2 on 2020-10-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.asset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.group')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('correct', models.BooleanField()),
                ('sequence_id', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.group')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.session')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.drug'),
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.group'),
        ),
    ]
