# Generated by Django 3.1.2 on 2020-10-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0003_auto_20201018_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.asset'),
        ),
        migrations.AddField(
            model_name='result',
            name='set_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrugID_API.set'),
        ),
    ]
