# Generated by Django 3.1.2 on 2020-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0004_auto_20201018_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='selected',
            field=models.CharField(default='Blank', max_length=100),
            preserve_default=False,
        ),
    ]
