# Generated by Django 3.1.2 on 2020-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0005_auto_20201018_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='set',
            name='asset_id',
            field=models.ManyToManyField(to='DrugID_API.Asset'),
        ),
    ]
