# Generated by Django 3.1.2 on 2020-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0006_auto_20201018_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='selected',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
