# Generated by Django 3.1.2 on 2023-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0007_auto_20201018_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_group',
            field=models.IntegerField(choices=[(1, 'Pharma'), (2, 'Iso'), (3, 'Black White')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_experience',
            field=models.IntegerField(null=True),
        ),
    ]
