# Generated by Django 3.1.2 on 2020-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugID_API', '0002_auto_20201017_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(choices=[('GAS', 'Anaesthetics'), ('A+E', 'Emergency Medicine'), ('ICM', 'Intensive Care'), ('OTH', 'Other')], default='GAS', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
